apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analytics-service
  namespace: argocd
  labels: { app.kubernetes.io/part-of: flashmarket }
spec:
  project: default
  source:
    repoURL: http://gitea-http.git.svc:3000/fm/flashmarket.git
    targetRevision: main
    path: helm/microservice
    helm:
      releaseName: analytics-service
      valueFiles: [ ../values/analytics-service.yaml ]
  destination:
    server: https://kubernetes.default.svc
    namespace: flashmarket
  syncPolicy:
    automated: { prune: true, selfHeal: true }
