apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-service
  namespace: argocd
  labels: { app.kubernetes.io/part-of: flashmarket }
spec:
  project: default
  source:
    repoURL: https://github.com/trouDever/se_sem2.git
    targetRevision: main
    path: helm/microservice
    helm:
      releaseName: catalog-service
      valueFiles: [ ../values/catalog-service.yaml ]
  destination:
    server: https://kubernetes.default.svc
    namespace: flashmarket
  syncPolicy:
    automated: { prune: true, selfHeal: true }
